site_name: patibanb.me
site_url: https://pbprasad99.github.io/algorithmic_pareto/
site_author: pbprasad99
site_description: Personal Website
repo_name: pbprasad99/algorithmic_pareto
repo_url: https://github.com/pbprasad99/algorithmic_pareto
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon : assets/images/favicon.
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: blue grey
    accent: blue grey
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: black
    accent: black
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.expand
  - navigation.indexes
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.copy
  - content.code.annotate
  icon:
    repo: fontawesome/brands/github
extra_css:
- assets/css/extra.css
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tabbed
- pymdownx.critic
- pymdownx.tasklist
- pymdownx.emoji
- admonition
- footnotes
- toc
- toc:
    permalink: true
plugins:
- search
- minify
- awesome-pages
- gen-files:
    scripts:
      - gen_pages.py
- blog
  # Add other plugins (like a theme) here
# - git-revision-date-localized:
#     enable_creation_date: true
