site_name: patibanb.me
site_url: https://pbprasad99.github.io/algorithmic_pareto/
site_author: pbprasad99
site_description: Personal Website
repo_name: pbprasad99/algorithmic_pareto
# repo_url: https://github.com/pbprasad99/algorithmic_pareto
# edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon : assets/images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: light blue
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light blue
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
  - navigation.instant
  #- navigation.tracking
  - navigation.tabs
  #- navigation.expand
  - navigation.path
  - navigation.indexes
  - navigation.footer
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.copy
  - content.code.annotate
  icon:
    repo: fontawesome/brands/github

hooks:
  - scripts/mkdocs_hooks.py

watch:
  - overrides/

extra_css:
- assets/stylesheets/extra.css
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic
- pymdownx.tasklist
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets
- admonition
- footnotes
- attr_list
- toc:
    permalink: true
plugins:
- search
# - markdown-exec
- minify
- awesome-nav
# - gen-files:
#     scripts:
#       - gen_pages.py
- blog:
    blog_toc: true
    post_url_format: "{slug}"
    post_excerpt: required
- social
- tags
- glightbox
  # Add other plugins (like a theme) here
# - git-revision-date-localized:
#     enable_creation_date: true
extra_javascript:
extra_javascript:
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://d3js.org/d3.v7.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
draft_docs: |
  drafts/               # A "drafts" directory anywhere.
  _unpublished.md       # A md file ending in _unpublished.md
  !/foo_unpublished.md  # But keep this particular file.